FROM ൽ ഫുസുഫ് / വ്ഹത്സസെന: പുതിയ

RUN git clone https://github.com/jineshkottarathil/devidjohn /root/WhatsAsenaDuplicated

WORKDIR /root/WhatsAsenaDuplicated/
ENV TZ=Europe/Istanbul
RUN npm install supervisor -g
RUN yarn install --no-audit

CMD ["node", "bot.js"]
